php_settings:
  version: 7.4
shared_dirs:
  mysite:
    cache: {}
crons:
  # Trigger regeneration expired cache entries every 10 minutes on a single machine
  static_cache_regen:
    time: "*/10 * * * *"
    sake_once: "dev/tasks/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask"
    vhost: "mysite"
  job_process_immediate:
    time: "*/2 * * * *"
    sake_once: "dev/tasks/ProcessJobQueueTask"
    vhost: "mysite"
  update_bucket:
    time: "*/30 * * * *"
    sake_once: "dev/tasks/UpdateBucket"
    vhost: "mysite"
whitelist:
  mysite:
    security:
      - "13.54.196.117"
    admin:
      - "13.54.196.117"
