php_settings:
  version: 7.4
shared_dirs:
  mysite:
    cache: {}
crons:
  # Trigger regeneration expired cache entries every 10 minutes on a single machine
  static_cache_regen:
    time: "*/10 * * * *"
    sake_once: "dev/tasks/SilverStripe-StaticPublishQueue-Task-StaticCacheFullBuildTask"
    vhost: "mysite"
  job_process_immediate:
    time: "*/2 * * * *"
    sake_once: "dev/tasks/ProcessJobQueueTask"
    vhost: "mysite"
whitelist:
  mysite:
    general:
      - "203.86.201.21"
      - "14.1.35.58"
    admin:
      - "203.86.201.21"
      - "14.1.35.58"
